language: 
  - python
python:
  - "2.7"
before_install:
  - sudo apt-get install cabal-install ghc 
  - cabal update
  - cabal install stack
install: 
  - ./installSubmodules.sh
  - pip install -r requirements.txt
# command to run tests
script: unit2
