Shorttalk_Letters = {
        "charm [<n>] ":          "c:%(n)d",
        "big charm [<n>] ":      "C:%(n)d",
        "(faye|fay) [<n>] ":     "f:%(n)d",
        "big (faye|fay) [<n>] ": "F:%(n)d",
        "ice [<n>] ":            "i:%(n)d",
        "big ice [<n>] ":        "I:%(n)d",
        "jo [<n>] ":             "j:%(n)d",
        "big jo [<n>] ":         "J:%(n)d",
        "(noy|neu) [<n>] ":      "n:%(n)d",
        "big (noy|neu) [<n>] ":  "N:%(n)d",
        "ork [<n>] ":            "o:%(n)d",
        "big ork [<n>] ":        "O:%(n)d",
        "pooch [<n>] ":          "p:%(n)d",
        "big pooch [<n>] ":      "P:%(n)d",
        "real [<n>] ":           "r:%(n)d",
        "big real [<n>] ":       "R:%(n)d",
        "(soi|soy) [<n>] ":      "s:%(n)d",
        "big (soi|soy) [<n>] ":  "S:%(n)d",
        "(take|teek|teak) [<n>] ":           "t:%(n)d",
        "big (take|teak|teek) [<n>] ":       "T:%(n)d",
        "uni [<n>] ":            "u:%(n)d",
        "big uni [<n>] ":        "U:%(n)d",
        "van [<n>] ":        "v:%(n)d",
        "big van [<n>] ":        "v:%(n)d",
        "war [<n>] ":            "w:%(n)d",
        "big war [<n>] ":        "W:%(n)d",
        "trex [<n>] ":           "x:%(n)d",
        "big trex [<n>] ":       "X:%(n)d",
        "yaa [<n>] ":            "y:%(n)d",
        "big yaa [<n>] ":        "Y:%(n)d",
}

Phonetic_Letter_map = {
    "(A|alpha|arch)":         "a",
    "big (A|alpha|arch)":     "A",
    "(B|bravo)":             "b",
    "big (B|bravo)":         "B",
    "(C|charlie)":            "c",
    "big (C|charlie)":        "C",
    "(D|delta)":             "d",
    "big (D|delta)":         "D",
    "(E|echo)":              "e",
    "big (E|echo)":          "E",
    "(F|foxtrot)":           "f",
    "big (F|foxtrot)":       "F",
    "(G|golf)":              "g",
    "big (G|golf)":          "G",
    "(H|hotel)":             "h",
    "big (H|hotel)":         "H",
    "(I|india|indigo)":      "i",
    "big (I|india|indigo)":  "I",
    "(J|juliet)":            "j",
    "big (J|juliet)":        "J",
    "(K|kilo)":              "k",
    "big (K|kilo)":          "K",
    "(L|lima)":              "l",
    "big (L|lima)":          "L",
    "(M|mike)":              "m",
    "big (M|mike)":          "M",
    "(N|november)":          "n",
    "big (N|november)":      "N",
    "(O|oscar)":             "o",
    "big (O|oscar)":         "O",
    "(P|papa|poppa)":        "p",
    "big (P|papa|poppa)":    "P",
    "(Q|quebec|quiche)":     "q",
    "big (Q|quebec|quiche)": "Q",
    "(R|romeo)":             "r",
    "big (R|romeo)":         "R",
    "(S|sierra|soy)":        "s",
    "big (S|sierra|soy)":    "S",
    "(T|tango)":             "t",
    "big (T|tango)":         "T",
    "(U|uniform)":           "u",
    "big (U|uniform)":       "U",
    "(V|victor|van)":        "v",
    "big (V|victor|van)":    "V",
    "(W|whiskey|wes)":       "w",
    "big (W|whiskey|wes)":   "W",
    "(X|x-ray)":             "x",
    "big (X|x-ray)":         "X",
    "(Y|yankee)":            "y",
    "big (Y|yankee)":        "Y",
    "(Z|zulu)":              "z",
    "big (Z|zulu)":          "Z",
}
